services:
  - type: web
    name: itc-ramadan-camp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://ramadan_qst_sl_user:yGnEizXLCsO47ecfU5TzPNQfLYBBUszV@dpg-d69t6bk9c44c738gpj1g-a.oregon-postgres.render.com/ramadan_qst_sl
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.13.10
